(function(){
  'use strict';
  const NS='http://www.w3.org/2000/svg', STORE='gedankenraum-map-v1';
  const el=id=>document.getElementById(id);
  const svg=el('mapSvg'), viewport=el('viewport'), nodeLayer=el('nodes'), connectionLayer=el('connections'), canvas=el('canvas');
  const palette=['#1f78d1','#18a58f','#e8a628','#e86558','#8857cf','#56647c'];
  let state, selectedId='root', history=[], future=[], drag=null, pan={x:0,y:0,scale:1}, saveTimer, lastTap={id:null,time:0}, pointers=new Map(), pinch=null;

  function nodeDefaults(n){return Object.assign({notesHtml:'',link:'',assignee:'',startDate:'',endDate:''},n)}
  function starter(){return {title:'Unterrichtsplanung · Klasse 9',nodes:[
    {id:'root',parentId:null,text:'Unterrichtsplanung',x:0,y:0,color:'#14213d'},
    {id:'n1',parentId:'root',text:'Lernziele',x:280,y:-160,color:palette[0]},
    {id:'n2',parentId:'root',text:'Inhalte',x:300,y:0,color:palette[1]},
    {id:'n3',parentId:'root',text:'Methoden',x:280,y:160,color:palette[3]},
    {id:'n4',parentId:'root',text:'Kompetenzen',x:-290,y:-100,color:palette[4]},
    {id:'n5',parentId:'root',text:'Leistungsnachweise',x:-310,y:100,color:palette[2]}
  ].map(nodeDefaults)};}
  function load(){try{const raw=localStorage.getItem(STORE);state=raw?JSON.parse(raw):starter();if(!state.nodes?.length)throw 0;state.nodes=state.nodes.map(nodeDefaults)}catch(e){state=starter()}el('mapTitle').value=state.title||'Meine Mindmap'}
  function snapshot(){history.push(JSON.stringify(state));if(history.length>60)history.shift();future=[];updateHistory()}
  function save(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{state.title=el('mapTitle').value.trim()||'Meine Mindmap';localStorage.setItem(STORE,JSON.stringify(state));},120)}
  function updateHistory(){el('undoBtn').disabled=!history.length;el('redoBtn').disabled=!future.length}
  function undo(){if(!history.length)return;future.push(JSON.stringify(state));state=JSON.parse(history.pop());selectedId=state.nodes.some(n=>n.id===selectedId)?selectedId:'root';el('mapTitle').value=state.title;render();save();updateHistory()}
  function redo(){if(!future.length)return;history.push(JSON.stringify(state));state=JSON.parse(future.pop());selectedId=state.nodes.some(n=>n.id===selectedId)?selectedId:'root';el('mapTitle').value=state.title;render();save();updateHistory()}
  function s(tag,attrs={}){const x=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>x.setAttribute(k,v));return x}
  function dims(n){const lines=wrap(n.text,22);return {w:n.id==='root'?210:Math.max(150,Math.min(230,80+Math.max(...lines.map(x=>x.length))*6.2)),h:Math.max(n.id==='root'?66:54,28+lines.length*19),lines}}
  function wrap(text,max){const words=(text||'Thema').trim().split(/\s+/),out=[];let line='';words.forEach(w=>{if((line+' '+w).trim().length>max&&line){out.push(line);line=w}else line=(line+' '+w).trim()});if(line)out.push(line);return out.slice(0,4)}
  function visibleNodes(){return state.nodes}
  function render(){
    connectionLayer.replaceChildren();nodeLayer.replaceChildren();
    visibleNodes().forEach(n=>{if(!n.parentId)return;const p=state.nodes.find(x=>x.id===n.parentId);if(!p)return;const pd=dims(p),nd=dims(n),right=n.x>=p.x;const x1=p.x+(right?pd.w/2:-pd.w/2),x2=n.x+(right?-nd.w/2:nd.w/2),bend=Math.max(45,Math.abs(x2-x1)*.48);const path=s('path',{d:`M ${x1} ${p.y} C ${x1+(right?bend:-bend)} ${p.y}, ${x2+(right?-bend:bend)} ${n.y}, ${x2} ${n.y}`,class:'connection',stroke:n.color});connectionLayer.append(path)});
    visibleNodes().forEach(n=>{const d=dims(n),g=s('g',{class:`node ${n.id==='root'?'root ':''}${n.id===selectedId?'selected':''}`,transform:`translate(${n.x} ${n.y})`,'data-id':n.id,tabindex:'0',role:'button','aria-label':n.text});const rect=s('rect',{class:'node-bg',x:-d.w/2,y:-d.h/2,width:d.w,height:d.h,rx:n.id==='root'?18:13,fill:n.color});g.append(rect);const text=s('text',{'text-anchor':'middle'});d.lines.forEach((line,i)=>{const t=s('tspan',{x:0,y:(i-(d.lines.length-1)/2)*19+6});t.textContent=line;text.append(t)});g.append(text);g.addEventListener('pointerdown',nodeDown);g.addEventListener('dblclick',()=>openEditor(n.id));g.addEventListener('keydown',e=>{if(e.key==='Enter')openEditor(n.id)});nodeLayer.append(g)});
    viewport.setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${pan.scale})`);syncInspector();
  }
  function syncInspector(){const n=state.nodes.find(x=>x.id===selectedId)||state.nodes[0];if(document.activeElement!==el('nodeText'))el('nodeText').value=n.text;if(document.activeElement!==el('nodeNotes'))el('nodeNotes').innerHTML=sanitizeNotes(n.notesHtml);if(document.activeElement!==el('nodeLink'))el('nodeLink').value=n.link||'';if(document.activeElement!==el('nodeAssignee'))el('nodeAssignee').value=n.assignee||'';if(document.activeElement!==el('nodeStart'))el('nodeStart').value=n.startDate||'';if(document.activeElement!==el('nodeEnd'))el('nodeEnd').value=n.endDate||'';el('openLinkBtn').disabled=!validLink(n.link);document.querySelectorAll('#colorPicker button').forEach(b=>b.classList.toggle('active',b.dataset.color.toLowerCase()===n.color.toLowerCase()));el('deleteBtn').disabled=n.id==='root';el('panelDeleteBtn').disabled=n.id==='root'}
  function screenToMap(clientX,clientY){const r=svg.getBoundingClientRect();return {x:(clientX-r.left-pan.x)/pan.scale,y:(clientY-r.top-pan.y)/pan.scale}}
  function nodeDown(e){e.stopPropagation();const id=e.currentTarget.dataset.id,now=Date.now();select(id);if(now-lastTap.time<330&&lastTap.id===id){openEditor(id);lastTap={id:null,time:0};return}lastTap={id,time:now};const n=state.nodes.find(x=>x.id===id),pt=screenToMap(e.clientX,e.clientY);drag={type:'node',id,dx:pt.x-n.x,dy:pt.y-n.y,moved:false,start:JSON.stringify(state)};e.currentTarget.setPointerCapture(e.pointerId)}
  function canvasDown(e){pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2){const points=[...pointers.values()],a=points[0],b=points[1],rect=svg.getBoundingClientRect();pinch={distance:Math.hypot(b.x-a.x,b.y-a.y),scale:pan.scale,startMid:{x:(a.x+b.x)/2-rect.left,y:(a.y+b.y)/2-rect.top},startPan:{x:pan.x,y:pan.y}};drag=null;canvas.setPointerCapture(e.pointerId);return}if(e.target.closest?.('.node'))return;drag={type:'pan',sx:e.clientX,sy:e.clientY,px:pan.x,py:pan.y};canvas.setPointerCapture(e.pointerId)}
  function pointerMove(e){if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch&&pointers.size>=2){const points=[...pointers.values()],a=points[0],b=points[1],rect=svg.getBoundingClientRect(),distance=Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),mid={x:(a.x+b.x)/2-rect.left,y:(a.y+b.y)/2-rect.top},next=Math.max(.35,Math.min(2.2,pinch.scale*distance/pinch.distance)),mapPoint={x:(pinch.startMid.x-pinch.startPan.x)/pinch.scale,y:(pinch.startMid.y-pinch.startPan.y)/pinch.scale};pan.scale=next;pan.x=mid.x-mapPoint.x*next;pan.y=mid.y-mapPoint.y*next;el('zoomLabel').textContent=Math.round(next*100)+' %';render();return}if(!drag)return;if(drag.type==='node'){const n=state.nodes.find(x=>x.id===drag.id),pt=screenToMap(e.clientX,e.clientY);n.x=Math.round(pt.x-drag.dx);n.y=Math.round(pt.y-drag.dy);drag.moved=true;render()}else{pan.x=drag.px+e.clientX-drag.sx;pan.y=drag.py+e.clientY-drag.sy;render()}}
  function pointerUp(e){pointers.delete(e.pointerId);if(pinch){if(pointers.size<2)pinch=null;drag=null;return}if(drag?.type==='node'&&drag.moved){history.push(drag.start);future=[];save();updateHistory()}drag=null}
  function select(id){selectedId=id;render()}
  function openEditor(id){select(id);el('inspector').classList.add('open');setTimeout(()=>{el('nodeText').focus();el('nodeText').select()},80)}
  function newId(){return 'n'+Date.now().toString(36)+Math.random().toString(36).slice(2,5)}
  function descendants(id){const ids=[];function walk(p){state.nodes.filter(n=>n.parentId===p).forEach(n=>{ids.push(n.id);walk(n.id)})}walk(id);return ids}
  function addBranch(){snapshot();const root=state.nodes.find(n=>n.id==='root'),children=state.nodes.filter(n=>n.parentId==='root'),right=children.filter(n=>n.x>=root.x).length<=children.filter(n=>n.x<root.x).length;const side=right?1:-1,count=children.filter(n=>(n.x>=root.x)===right).length;const id=newId();state.nodes.push(nodeDefaults({id,parentId:'root',text:'Neues Hauptthema',x:root.x+side*(290+count*16),y:root.y+(count-Math.floor(children.length/2))*110,color:palette[children.length%palette.length]}));selectedId=id;render();save();openEditor(id)}
  function addChild(){const p=state.nodes.find(n=>n.id===selectedId)||state.nodes[0];snapshot();const kids=state.nodes.filter(n=>n.parentId===p.id),side=p.id==='root'?1:(p.x>=state.nodes[0].x?1:-1);const id=newId();state.nodes.push(nodeDefaults({id,parentId:p.id,text:'Neues Unterthema',x:p.x+side*245,y:p.y+(kids.length-(kids.length?0:.5))*82,color:p.id==='root'?palette[kids.length%palette.length]:p.color}));selectedId=id;render();save();openEditor(id)}
  function removeNode(){if(selectedId==='root')return;const n=state.nodes.find(x=>x.id===selectedId);if(!n)return;snapshot();const gone=[selectedId,...descendants(selectedId)];selectedId=n.parentId||'root';state.nodes=state.nodes.filter(x=>!gone.includes(x.id));render();save();toast(gone.length>1?'Themen gelöscht':'Thema gelöscht')}
  function setZoom(next,cx,cy){const old=pan.scale;next=Math.max(.35,Math.min(2.2,next));const r=svg.getBoundingClientRect(),x=cx??r.width/2,y=cy??r.height/2;pan.x=x-(x-pan.x)*(next/old);pan.y=y-(y-pan.y)*(next/old);pan.scale=next;el('zoomLabel').textContent=Math.round(next*100)+' %';render()}
  function fit(){const nodes=visibleNodes();if(!nodes.length)return;const boxes=nodes.map(n=>{const d=dims(n);return {l:n.x-d.w/2,r:n.x+d.w/2,t:n.y-d.h/2,b:n.y+d.h/2}}),minX=Math.min(...boxes.map(b=>b.l)),maxX=Math.max(...boxes.map(b=>b.r)),minY=Math.min(...boxes.map(b=>b.t)),maxY=Math.max(...boxes.map(b=>b.b)),r=svg.getBoundingClientRect(),pad=80;pan.scale=Math.max(.35,Math.min(1.25,Math.min((r.width-pad)/(maxX-minX||1),(r.height-pad)/(maxY-minY||1))));pan.x=r.width/2-(minX+maxX)/2*pan.scale;pan.y=r.height/2-(minY+maxY)/2*pan.scale;el('zoomLabel').textContent=Math.round(pan.scale*100)+' %';render()}
  function reset(){if(!confirm('Eine neue Mindmap beginnen? Die aktuelle Mindmap kann vorher als Datei gesichert werden.'))return;snapshot();state={title:'Meine Mindmap',nodes:[{id:'root',parentId:null,text:'Meine Mindmap',x:0,y:0,color:'#14213d'}]};selectedId='root';el('mapTitle').value=state.title;render();fit();save()}
  function validLink(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)}catch(e){return false}}
  function sanitizeNotes(html){const doc=new DOMParser().parseFromString(String(html||''),'text/html');const allowed=['B','STRONG','I','EM','U','BR','P','UL','OL','LI','A'];doc.body.querySelectorAll('*').forEach(node=>{if(!allowed.includes(node.tagName)){node.replaceWith(...node.childNodes)}else{[...node.attributes].forEach(attr=>{if(node.tagName==='A'&&attr.name==='href'&&validLink(attr.value))return;node.removeAttribute(attr.name)});if(node.tagName==='A'&&!validLink(node.getAttribute('href')||''))node.replaceWith(...node.childNodes)}});return doc.body.innerHTML}
  function setNodeField(key,value){const n=state.nodes.find(x=>x.id===selectedId);if(!n)return;snapshot();n[key]=value;render();save()}
  function markdownText(html){const doc=new DOMParser().parseFromString(sanitizeNotes(html),'text/html');function walk(node,depth=0){if(node.nodeType===3)return node.nodeValue.replace(/\s+/g,' ');if(node.nodeType!==1)return [...node.childNodes].map(n=>walk(n,depth)).join('');const inner=[...node.childNodes].map(n=>walk(n,depth)).join('');switch(node.tagName){case'BR':return '\n';case'B':case'STRONG':return `**${inner.trim()}**`;case'I':case'EM':return `*${inner.trim()}*`;case'U':return `<u>${inner.trim()}</u>`;case'LI':return `- ${inner.trim()}\n`;case'P':return `${inner.trim()}\n\n`;case'UL':case'OL':return `${inner}\n`;case'A':return validLink(node.getAttribute('href')||'')?`[${inner.trim()}](${node.getAttribute('href')})`:inner;default:return inner}}return walk(doc.body).replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
  function downloadText(name,text,type){const blob=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function exportMarkdown(){state.title=el('mapTitle').value.trim()||'Meine Mindmap';const lines=[`# ${state.title}`,''];function add(id,level){const n=state.nodes.find(x=>x.id===id);if(!n)return;const pad='  '.repeat(level);lines.push(`${pad}- **${n.text}**`);if(n.assignee)lines.push(`${pad}  - Verantwortlich: ${n.assignee}`);if(n.startDate||n.endDate)lines.push(`${pad}  - Zeitraum: ${n.startDate||'offen'} bis ${n.endDate||'offen'}`);if(validLink(n.link))lines.push(`${pad}  - Ziel: [Link](${n.link})`);const note=markdownText(n.notesHtml);if(note)lines.push(`${pad}  - Notiz: ${note.split('\n').join(`\n${pad}    `)}`);state.nodes.filter(x=>x.parentId===id).forEach(child=>add(child.id,level+1))}add('root',0);downloadText(`${safeName(state.title)}.md`,lines.join('\n')+'\n','text/markdown;charset=utf-8');toast('Markdown-Datei gesichert')}
  function dateValue(value){const date=new Date(`${value}T00:00:00`);return Number.isNaN(date.getTime())?null:date}
  function dateLabel(date){return `${String(date.getDate()).padStart(2,'0')}.${String(date.getMonth()+1).padStart(2,'0')}`}
  function renderGantt(){const dated=state.nodes.filter(n=>dateValue(n.startDate)&&dateValue(n.endDate)&&dateValue(n.endDate)>=dateValue(n.startDate));el('ganttView').replaceChildren();el('ganttEmpty').hidden=dated.length>0;if(!dated.length)return;const min=new Date(Math.min(...dated.map(n=>dateValue(n.startDate).getTime()))),max=new Date(Math.max(...dated.map(n=>dateValue(n.endDate).getTime()))),days=Math.round((max-min)/86400000)+1;const header=document.createElement('div');header.className='gantt-header';const title=document.createElement('div');title.className='gantt-label';title.textContent='Thema';const daysEl=document.createElement('div');daysEl.className='gantt-days';for(let i=0;i<days;i++){const d=new Date(min);d.setDate(d.getDate()+i);const cell=document.createElement('div');cell.className='gantt-day';cell.textContent=dateLabel(d);daysEl.append(cell)}header.append(title,daysEl);el('ganttView').append(header);dated.forEach(n=>{const row=document.createElement('div');row.className='gantt-row';const label=document.createElement('div');label.className='gantt-label';label.title=n.assignee?`${n.text} · ${n.assignee}`:n.text;label.textContent=n.assignee?`${n.text} · ${n.assignee}`:n.text;const track=document.createElement('div');track.className='gantt-timeline';const start=Math.round((dateValue(n.startDate)-min)/86400000),span=Math.round((dateValue(n.endDate)-dateValue(n.startDate))/86400000)+1;const bar=document.createElement('div');bar.className='gantt-bar';bar.style.left=`${start*38+3}px`;bar.style.width=`${Math.max(span*38-6,22)}px`;bar.style.background=n.color||palette[0];bar.textContent=n.text;track.append(bar);row.append(label,track);el('ganttView').append(row)})}
  function openGantt(){renderGantt();el('ganttModal').hidden=false}
  function closeGantt(){el('ganttModal').hidden=true}
  function exportGanttMarkdown(){const title=el('mapTitle').value.trim()||'Meine Mindmap';const dated=state.nodes.filter(n=>n.startDate||n.endDate);const lines=[`# Ganttplan: ${title}`,'','| Thema | Verantwortlich | Start | Ende | Ziel |','|---|---|---|---|---|',...dated.map(n=>`| ${n.text.replaceAll('|','\\|')} | ${(n.assignee||'').replaceAll('|','\\|')} | ${n.startDate||''} | ${n.endDate||''} | ${validLink(n.link)?n.link:''} |`)];downloadText(`${safeName(title)}-gantt.md`,lines.join('\n')+'\n','text/markdown;charset=utf-8');toast('Ganttplan als Markdown gesichert')}
  function exportJson(){state.title=el('mapTitle').value.trim()||'Meine Mindmap';const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=safeName(state.title)+'.mindmap.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Mindmap-Datei gesichert')}
  function importJson(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.nodes)||!data.nodes.some(n=>n.id==='root'))throw 0;snapshot();state=Object.assign(data,{nodes:data.nodes.map(nodeDefaults)});selectedId='root';el('mapTitle').value=data.title||'Meine Mindmap';render();fit();save();toast('Mindmap geöffnet')}catch(e){alert('Diese Datei ist keine gültige Gedankenraum-Mindmap.')}};reader.readAsText(file)}
  function safeName(v){return v.replace(/[^a-z0-9äöüß_ -]/gi,'').trim().replace(/\s+/g,'-')||'Mindmap'}
  function mapBounds(){const boxes=visibleNodes().map(n=>{const d=dims(n);return {l:n.x-d.w/2,r:n.x+d.w/2,t:n.y-d.h/2,b:n.y+d.h/2}});return {minX:Math.min(...boxes.map(b=>b.l)),maxX:Math.max(...boxes.map(b=>b.r)),minY:Math.min(...boxes.map(b=>b.t)),maxY:Math.max(...boxes.map(b=>b.b))}}
  function preparePrint(){const b=mapBounds(),pad=55;svg.setAttribute('viewBox',`${b.minX-pad} ${b.minY-pad} ${b.maxX-b.minX+pad*2} ${b.maxY-b.minY+pad*2}`);viewport.removeAttribute('transform');document.querySelectorAll('.node').forEach(n=>n.classList.remove('selected'))}
  function finishPrint(){svg.removeAttribute('viewBox');render()}
  function exportPdf(){toast('Druckansicht wird geöffnet …');setTimeout(()=>window.print(),180)}
  function toast(msg){const t=el('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}
  function bind(){
    canvas.addEventListener('pointerdown',canvasDown,true);window.addEventListener('pointermove',pointerMove);window.addEventListener('pointerup',pointerUp);window.addEventListener('pointercancel',pointerUp);canvas.addEventListener('wheel',e=>{e.preventDefault();const r=svg.getBoundingClientRect();setZoom(pan.scale*(e.deltaY<0?1.1:.9),e.clientX-r.left,e.clientY-r.top)},{passive:false});
    [['branchBtn',addBranch],['mobileBranch',addBranch],['childBtn',addChild],['mobileChild',addChild],['panelChildBtn',addChild],['deleteBtn',removeNode],['panelDeleteBtn',removeNode],['fitBtn',fit],['miniFit',fit],['pdfBtn',exportPdf],['mobilePdf',exportPdf],['saveBtn',exportJson],['mobileSave',exportJson],['markdownBtn',exportMarkdown],['ganttBtn',openGantt],['newBtn',reset],['undoBtn',undo],['redoBtn',redo]].forEach(([id,fn])=>el(id).addEventListener('click',fn));
    [['zoomInBtn',1.15],['miniPlus',1.15],['zoomOutBtn',.87],['miniMinus',.87]].forEach(([id,m])=>el(id).addEventListener('click',()=>setZoom(pan.scale*m)));
    el('nodeText').addEventListener('input',e=>{const n=state.nodes.find(x=>x.id===selectedId);if(n){n.text=e.target.value||'Thema';render();save()}});el('nodeText').addEventListener('focus',()=>{el('nodeText').dataset.before=JSON.stringify(state)});el('nodeText').addEventListener('change',e=>{const before=e.target.dataset.before;if(before){history.push(before);future=[];updateHistory();delete e.target.dataset.before}});
    el('nodeNotes').addEventListener('focus',()=>{el('nodeNotes').dataset.before=JSON.stringify(state)});el('nodeNotes').addEventListener('input',e=>{const n=state.nodes.find(x=>x.id===selectedId);if(n){n.notesHtml=sanitizeNotes(e.currentTarget.innerHTML);save()}});el('nodeNotes').addEventListener('blur',e=>{const before=e.currentTarget.dataset.before;if(before){history.push(before);future=[];updateHistory();delete e.currentTarget.dataset.before}});
    [['nodeLink','link'],['nodeAssignee','assignee'],['nodeStart','startDate'],['nodeEnd','endDate']].forEach(([id,key])=>el(id).addEventListener('change',e=>setNodeField(key,key==='link'&&!validLink(e.target.value)?'':e.target.value.trim())));
    document.querySelectorAll('[data-format]').forEach(button=>button.addEventListener('mousedown',e=>e.preventDefault()));document.querySelectorAll('[data-format]').forEach(button=>button.addEventListener('click',()=>{el('nodeNotes').focus();document.execCommand(button.dataset.format,false,null);el('nodeNotes').dispatchEvent(new Event('input',{bubbles:true}))}));
    el('openLinkBtn').addEventListener('click',()=>{const n=state.nodes.find(x=>x.id===selectedId);if(validLink(n?.link))window.open(n.link,'_blank','noopener,noreferrer')});
    el('mapTitle').addEventListener('input',save);el('colorPicker').addEventListener('click',e=>{const b=e.target.closest('button[data-color]');if(!b)return;snapshot();state.nodes.find(x=>x.id===selectedId).color=b.dataset.color;render();save()});
    el('closeInspector').addEventListener('click',()=>el('inspector').classList.remove('open'));el('editBtn').addEventListener('click',()=>openEditor(selectedId));
    el('importBtn').addEventListener('click',()=>el('fileInput').click());el('mobileOpen').addEventListener('click',()=>el('fileInput').click());el('fileInput').addEventListener('change',e=>{if(e.target.files[0])importJson(e.target.files[0]);e.target.value=''});
    el('moreBtn').addEventListener('click',()=>{const m=el('actionMenu');m.hidden=!m.hidden});el('actionMenu').addEventListener('click',e=>{const a=e.target.dataset.action;if(!a)return;el('actionMenu').hidden=true;({new:reset,import:()=>el('fileInput').click(),save:exportJson,markdown:exportMarkdown,gantt:openGantt,fit})[a]()});
    el('closeGantt').addEventListener('click',closeGantt);el('ganttModal').addEventListener('click',e=>{if(e.target===el('ganttModal'))closeGantt()});el('printGantt').addEventListener('click',()=>window.print());el('exportGanttMarkdown').addEventListener('click',exportGanttMarkdown);
    document.addEventListener('click',e=>{if(!e.target.closest('#moreBtn')&&!e.target.closest('#actionMenu'))el('actionMenu').hidden=true});
    document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA/.test(e.target.tagName))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if(e.key==='Delete'||e.key==='Backspace')removeNode();else if(e.key==='Tab'){e.preventDefault();addChild()}else if(e.key==='Enter')openEditor(selectedId)});
    window.addEventListener('resize',()=>setTimeout(fit,80));window.addEventListener('beforeprint',preparePrint);window.addEventListener('afterprint',finishPrint);
  }
  function registerWebMcp(){
    const context=document.modelContext;if(!context?.registerTool)return;
    const register=tool=>{try{void Promise.resolve(context.registerTool(tool)).catch(()=>{})}catch(e){}}
    register({name:'read_mindmap',title:'Mindmap lesen',description:'Liest Titel und Themen der aktuell geöffneten Mindmap.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return {title:state.title,nodes:state.nodes.map(({id,parentId,text})=>({id,parentId,text}))}}});
    register({name:'add_mindmap_topics',title:'Themen hinzufügen',description:'Fügt der sichtbaren Mindmap mehrere Themen als Kinder eines vorhandenen Themas hinzu.',inputSchema:{type:'object',properties:{parentId:{type:'string'},topics:{type:'array',minItems:1,maxItems:20,items:{type:'string',minLength:1,maxLength:180}}},required:['parentId','topics'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.parentId!=='string'||!Array.isArray(input.topics)||!input.topics.length||input.topics.length>20)throw new Error('Ungültige Eingabe');const p=state.nodes.find(n=>n.id===input.parentId);if(!p)throw new Error('Übergeordnetes Thema nicht gefunden');if(input.topics.some(t=>typeof t!=='string'||!t.trim()||t.length>180))throw new Error('Ungültiger Thementext');snapshot();const side=p.id==='root'?1:(p.x>=state.nodes[0].x?1:-1),existing=state.nodes.filter(n=>n.parentId===p.id).length,ids=[];input.topics.forEach((text,i)=>{const id=newId();ids.push(id);state.nodes.push({id,parentId:p.id,text:text.trim(),x:p.x+side*245,y:p.y+(existing+i-(input.topics.length-1)/2)*82,color:p.id==='root'?palette[(existing+i)%palette.length]:p.color})});selectedId=ids[0];render();save();return {added:ids.length,nodeIds:ids}}});
  }
  function enableOffline(){
    if(!('serviceWorker' in navigator)||location.protocol!=='https:')return;
    navigator.serviceWorker.register('./service-worker.js',{scope:'./'}).then(reg=>{
      const markReady=()=>{el('offlineBadge').classList.add('ready')};
      if(reg.active)markReady();
      navigator.serviceWorker.ready.then(()=>{markReady();if(!localStorage.getItem('gedankenraum-offline-notice')){localStorage.setItem('gedankenraum-offline-notice','1');toast('Die App ist jetzt offline verfügbar')}});
    }).catch(()=>{});
  }
  load();bind();render();updateHistory();registerWebMcp();enableOffline();requestAnimationFrame(fit);
})();
